{% set name = "apache-airflow-task-sdk" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_task_sdk-{{ version }}.tar.gz
  sha256: 44b4d8222397e0835dc0b88e833eed54b5cb2ac90f13d3d46355a03fb2fb06f5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<3.13
    # circular dependency, so we'll exclude it for now
    # - apache-airflow-core <=3.1.0,>=3.0.0
    - aiologic >=0.14.0
    - attrs >=24.2.0,!=25.2.0
    - fsspec >=2023.10.0
    - httpx >=0.27.0
    - jinja2 >=3.1.5
    - methodtools >=0.4.7
    - msgspec >=0.19.0
    # stricter requrement for py>=3.12 to stay noarch: python
    - pendulum >=3.0.0,<4.0
    - python-dateutil >=2.7.0
    - psutil >=6.1.0
    - structlog >=25.2.0
    - retryhttp >=1.2.0,!=1.3.0

test:
  imports:
    - airflow.sdk
  commands:
    # skipping pip check for now because of circular dependencies
    # - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow
  summary: Python Task SDK for Apache Airflow DAG Authors
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/apache/airflow
  doc_url: https://github.com/apache/airflow/blob/main/task-sdk/README.md

extra:
  recipe-maintainers:
    - xylar
