{% set name = "apache-airflow-task-sdk" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_task_sdk-{{ version }}.tar.gz
  sha256: 962234b68260b311c09401c571b67b2ec5864b410fa1aa26abf92d1782f51628

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<3.14
    - apache-airflow-core <3.2.0,>=3.1.2
    - asgiref >=2.3.0
    - attrs >=24.2.0,!=25.2.0
    - babel >=2.17.0
    - fsspec >=2023.10.0
    - httpx >=0.27.0
    - jinja2 >=3.1.5
    - methodtools >=0.4.7
    - msgspec >=0.19.0
    - python-dateutil >=2.7.0
    - psutil >=6.1.0
    - structlog >=25.4.0
    - greenback >=1.2.1
    - tenacity >=8.3.0
    - pendulum >=3.1.0
    - colorlog >=6.8.2
    - pydantic >2.11.0
    - pygtrie >=2.5.0

test:
  imports:
    - airflow.sdk
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow
  summary: Python Task SDK for Apache Airflow DAG Authors
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/apache/airflow
  doc_url: https://github.com/apache/airflow/blob/main/task-sdk/README.md

extra:
  recipe-maintainers:
    - xylar
