schema_version: 1

context:
  name: apache-airflow-task-sdk
  version: 1.1.5

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_task_sdk-${{ version }}.tar.gz
  sha256: 4a4d31c07f3b7c51374f74635d70e1f2ffb25f116dc50f1310533ee3c63258d8

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<3.14
    - apache-airflow-core <3.2.0,>=3.1.5
    - asgiref >=2.3.0
    - attrs >=24.2.0,!=25.2.0
    - babel >=2.17.0
    - fsspec >=2023.10.0
    - httpx >=0.27.0
    - jinja2 >=3.1.5
    - methodtools >=0.4.7
    - msgspec >=0.19.0
    - python-dateutil >=2.7.0
    - psutil >=6.1.0
    - structlog >=25.4.0
    - greenback >=1.2.1
    - tenacity >=8.3.0
    - pendulum >=3.1.0
    - colorlog >=6.8.2
    - pydantic >2.11.0
    - pygtrie >=2.5.0

tests:
  - python:
      imports:
        - airflow.sdk
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip check

about:
  summary: Python Task SDK for Apache Airflow DAG Authors
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/apache/airflow
  repository: https://github.com/apache/airflow
  documentation: https://github.com/apache/airflow/blob/main/task-sdk/README.md

extra:
  recipe-maintainers:
    - xylar
